name: chomik
description: "Lista połączeń"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.22+22

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  call_log: ^4.0.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  intl: ^0.19.0
  phone_state_background: ^0.0.4
  path_provider: ^2.1.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/Chomik.png
