name: chomik
description: "Lista połączeń"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.32+32

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.3
  http: ^1.2.0
  intl: ^0.19.0
  phone_state_background: ^0.0.4
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  call_log: ^4.0.0
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  package_info_plus: ^8.1.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4
  path: ^1.9.0
  connectivity_plus: ^6.1.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Chomik.png
