name: chomik
description: "Lista połączeń"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.37+37

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.3
  http: ^1.2.0
  intl: ^0.19.0
  phone_state_background: ^0.0.4
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  call_log: ^6.0.0
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  package_info_plus: ^8.1.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  connectivity_plus: ^6.1.1
  window_manager: ^0.5.0
  flutter_sound: ^9.17.8
  flutter_sound_platform_interface: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Chomik.png
